// <auto-generated />
using Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(HolidayHomeDbContext))]
    [Migration("20250703132111_checkchanges")]
    partial class checkchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Data.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccommodationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedSheetsAvailability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hints")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDogAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonSmoking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsParkingAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSaunaAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTelevisionAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWashingMachineAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWifiAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KitchenTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LandLordName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfLivingRooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfMixedRooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortTripAvailability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquareMeter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TowelsAvailability")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationTypeId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("KitchenTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("Data.Models.AccommodationSanitaryInfo", b =>
                {
                    b.Property<int>("AccommodationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SanitaryTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccommodationId", "SanitaryTypeId");

                    b.HasIndex("SanitaryTypeId");

                    b.ToTable("AccommodationSanitaryInfos");
                });

            modelBuilder.Entity("Data.Models.AccommodationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("AccommodationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "FH",
                            Title = "Ferienhaus"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "FW",
                            Title = "Ferienwohnung"
                        });
                });

            modelBuilder.Entity("Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Street", "City")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Data.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Data.Models.KitchenType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("KitchenTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Kü",
                            Title = "Küche"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "Kn",
                            Title = "Kochnische"
                        });
                });

            modelBuilder.Entity("Data.Models.SanitaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("SanitaryTypes");
                });

            modelBuilder.Entity("Data.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Data.Models.SeasonPricing", b =>
                {
                    b.Property<int>("AccommodationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBookable")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("AccommodationId", "SeasonId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonPricings");
                });

            modelBuilder.Entity("Data.Models.Accommodation", b =>
                {
                    b.HasOne("Data.Models.AccommodationType", "AccommodationType")
                        .WithMany("Accommodations")
                        .HasForeignKey("AccommodationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Address", "Address")
                        .WithOne("Accommodation")
                        .HasForeignKey("Data.Models.Accommodation", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.KitchenType", "KitchenType")
                        .WithMany()
                        .HasForeignKey("KitchenTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccommodationType");

                    b.Navigation("Address");

                    b.Navigation("KitchenType");
                });

            modelBuilder.Entity("Data.Models.AccommodationSanitaryInfo", b =>
                {
                    b.HasOne("Data.Models.Accommodation", "Accommodation")
                        .WithMany("AccommodationSanitaryInfos")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.SanitaryType", "SanitaryType")
                        .WithMany("AccommodationSanitaryInfos")
                        .HasForeignKey("SanitaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("SanitaryType");
                });

            modelBuilder.Entity("Data.Models.Image", b =>
                {
                    b.HasOne("Data.Models.Accommodation", "Accommodation")
                        .WithMany("Images")
                        .HasForeignKey("AccommodationId");

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("Data.Models.SeasonPricing", b =>
                {
                    b.HasOne("Data.Models.Accommodation", "Accommodation")
                        .WithMany("SeasonPricings")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Season", "Season")
                        .WithMany("SeasonPricings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Data.Models.Accommodation", b =>
                {
                    b.Navigation("AccommodationSanitaryInfos");

                    b.Navigation("Images");

                    b.Navigation("SeasonPricings");
                });

            modelBuilder.Entity("Data.Models.AccommodationType", b =>
                {
                    b.Navigation("Accommodations");
                });

            modelBuilder.Entity("Data.Models.Address", b =>
                {
                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("Data.Models.SanitaryType", b =>
                {
                    b.Navigation("AccommodationSanitaryInfos");
                });

            modelBuilder.Entity("Data.Models.Season", b =>
                {
                    b.Navigation("SeasonPricings");
                });
#pragma warning restore 612, 618
        }
    }
}
